/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppDataBackupRouteImport } from './routes/app/data-backup'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSyncRouteImport } from './routes/app/sync'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AppConversationsIndexRouteImport } from './routes/app/conversations.index'
import { Route as AppConversationsNewRouteImport } from './routes/app/conversations.new'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages.index'
import { Route as AppMessagesNewRouteImport } from './routes/app/messages.new'
import { Route as AppParticipantsIndexRouteImport } from './routes/app/participants.index'
import { Route as AppParticipantsNewRouteImport } from './routes/app/participants.new'
import { Route as AppSystemIndexRouteImport } from './routes/app/system.index'
import { Route as AppSystemActivityRouteImport } from './routes/app/system.activity'
import { Route as AppSystemCronRouteImport } from './routes/app/system.cron'
import { Route as AppSystemDashboardSettingsRouteImport } from './routes/app/system.dashboard-settings'
import { Route as AppSystemFilesRouteImport } from './routes/app/system.files'
import { Route as AppSystemHealthRouteImport } from './routes/app/system.health'
import { Route as AppSystemJobsRouteImport } from './routes/app/system.jobs'
import { Route as AppSystemNotificationsRouteImport } from './routes/app/system.notifications'
import { Route as AppSystemPerformanceRouteImport } from './routes/app/system.performance'
import { Route as AppSystemRolesRouteImport } from './routes/app/system.roles'
import { Route as AppSystemSecurityRouteImport } from './routes/app/system.security'
import { Route as AppSystemSupportRouteImport } from './routes/app/system.support'
import { Route as AppSystemUsersRouteImport } from './routes/app/system.users'
import { Route as AppConversationsIdEditRouteImport } from './routes/app/conversations.$id.edit'
import { Route as AppMessagesIdEditRouteImport } from './routes/app/messages.$id.edit'
import { Route as AppParticipantsIdEditRouteImport } from './routes/app/participants.$id.edit'
import { Route as AppSystemSupportIdRouteImport } from './routes/app/system.support.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDataBackupRoute = AppDataBackupRouteImport.update({
  id: '/data-backup',
  path: '/data-backup',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AppConversationsIndexRoute = AppConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsNewRoute = AppConversationsNewRouteImport.update({
  id: '/conversations/new',
  path: '/conversations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesNewRoute = AppMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsIndexRoute = AppParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsNewRoute = AppParticipantsNewRouteImport.update({
  id: '/participants/new',
  path: '/participants/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemIndexRoute = AppSystemIndexRouteImport.update({
  id: '/system/',
  path: '/system/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemActivityRoute = AppSystemActivityRouteImport.update({
  id: '/system/activity',
  path: '/system/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemCronRoute = AppSystemCronRouteImport.update({
  id: '/system/cron',
  path: '/system/cron',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemDashboardSettingsRoute =
  AppSystemDashboardSettingsRouteImport.update({
    id: '/system/dashboard-settings',
    path: '/system/dashboard-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppSystemFilesRoute = AppSystemFilesRouteImport.update({
  id: '/system/files',
  path: '/system/files',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemHealthRoute = AppSystemHealthRouteImport.update({
  id: '/system/health',
  path: '/system/health',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemJobsRoute = AppSystemJobsRouteImport.update({
  id: '/system/jobs',
  path: '/system/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemNotificationsRoute = AppSystemNotificationsRouteImport.update({
  id: '/system/notifications',
  path: '/system/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemPerformanceRoute = AppSystemPerformanceRouteImport.update({
  id: '/system/performance',
  path: '/system/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRolesRoute = AppSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSecurityRoute = AppSystemSecurityRouteImport.update({
  id: '/system/security',
  path: '/system/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSupportRoute = AppSystemSupportRouteImport.update({
  id: '/system/support',
  path: '/system/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemUsersRoute = AppSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsIdEditRoute = AppConversationsIdEditRouteImport.update({
  id: '/conversations/$id/edit',
  path: '/conversations/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdEditRoute = AppMessagesIdEditRouteImport.update({
  id: '/messages/$id/edit',
  path: '/messages/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantsIdEditRoute = AppParticipantsIdEditRouteImport.update({
  id: '/participants/$id/edit',
  path: '/participants/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSupportIdRoute = AppSystemSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSystemSupportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/data-backup': typeof AppDataBackupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sync': typeof AppSyncRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/conversations/new': typeof AppConversationsNewRoute
  '/app/messages/new': typeof AppMessagesNewRoute
  '/app/participants/new': typeof AppParticipantsNewRoute
  '/app/system/activity': typeof AppSystemActivityRoute
  '/app/system/cron': typeof AppSystemCronRoute
  '/app/system/dashboard-settings': typeof AppSystemDashboardSettingsRoute
  '/app/system/files': typeof AppSystemFilesRoute
  '/app/system/health': typeof AppSystemHealthRoute
  '/app/system/jobs': typeof AppSystemJobsRoute
  '/app/system/notifications': typeof AppSystemNotificationsRoute
  '/app/system/performance': typeof AppSystemPerformanceRoute
  '/app/system/roles': typeof AppSystemRolesRoute
  '/app/system/security': typeof AppSystemSecurityRoute
  '/app/system/support': typeof AppSystemSupportRouteWithChildren
  '/app/system/users': typeof AppSystemUsersRoute
  '/app/conversations/': typeof AppConversationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/participants/': typeof AppParticipantsIndexRoute
  '/app/system/': typeof AppSystemIndexRoute
  '/app/conversations/$id/edit': typeof AppConversationsIdEditRoute
  '/app/messages/$id/edit': typeof AppMessagesIdEditRoute
  '/app/participants/$id/edit': typeof AppParticipantsIdEditRoute
  '/app/system/support/$id': typeof AppSystemSupportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/data-backup': typeof AppDataBackupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sync': typeof AppSyncRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/conversations/new': typeof AppConversationsNewRoute
  '/app/messages/new': typeof AppMessagesNewRoute
  '/app/participants/new': typeof AppParticipantsNewRoute
  '/app/system/activity': typeof AppSystemActivityRoute
  '/app/system/cron': typeof AppSystemCronRoute
  '/app/system/dashboard-settings': typeof AppSystemDashboardSettingsRoute
  '/app/system/files': typeof AppSystemFilesRoute
  '/app/system/health': typeof AppSystemHealthRoute
  '/app/system/jobs': typeof AppSystemJobsRoute
  '/app/system/notifications': typeof AppSystemNotificationsRoute
  '/app/system/performance': typeof AppSystemPerformanceRoute
  '/app/system/roles': typeof AppSystemRolesRoute
  '/app/system/security': typeof AppSystemSecurityRoute
  '/app/system/support': typeof AppSystemSupportRouteWithChildren
  '/app/system/users': typeof AppSystemUsersRoute
  '/app/conversations': typeof AppConversationsIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/participants': typeof AppParticipantsIndexRoute
  '/app/system': typeof AppSystemIndexRoute
  '/app/conversations/$id/edit': typeof AppConversationsIdEditRoute
  '/app/messages/$id/edit': typeof AppMessagesIdEditRoute
  '/app/participants/$id/edit': typeof AppParticipantsIdEditRoute
  '/app/system/support/$id': typeof AppSystemSupportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/chat': typeof AppChatRoute
  '/app/data-backup': typeof AppDataBackupRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/sync': typeof AppSyncRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/conversations/new': typeof AppConversationsNewRoute
  '/app/messages/new': typeof AppMessagesNewRoute
  '/app/participants/new': typeof AppParticipantsNewRoute
  '/app/system/activity': typeof AppSystemActivityRoute
  '/app/system/cron': typeof AppSystemCronRoute
  '/app/system/dashboard-settings': typeof AppSystemDashboardSettingsRoute
  '/app/system/files': typeof AppSystemFilesRoute
  '/app/system/health': typeof AppSystemHealthRoute
  '/app/system/jobs': typeof AppSystemJobsRoute
  '/app/system/notifications': typeof AppSystemNotificationsRoute
  '/app/system/performance': typeof AppSystemPerformanceRoute
  '/app/system/roles': typeof AppSystemRolesRoute
  '/app/system/security': typeof AppSystemSecurityRoute
  '/app/system/support': typeof AppSystemSupportRouteWithChildren
  '/app/system/users': typeof AppSystemUsersRoute
  '/app/conversations/': typeof AppConversationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/participants/': typeof AppParticipantsIndexRoute
  '/app/system/': typeof AppSystemIndexRoute
  '/app/conversations/$id/edit': typeof AppConversationsIdEditRoute
  '/app/messages/$id/edit': typeof AppMessagesIdEditRoute
  '/app/participants/$id/edit': typeof AppParticipantsIdEditRoute
  '/app/system/support/$id': typeof AppSystemSupportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/chat'
    | '/app/data-backup'
    | '/app/profile'
    | '/app/settings'
    | '/app/sync'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/conversations/new'
    | '/app/messages/new'
    | '/app/participants/new'
    | '/app/system/activity'
    | '/app/system/cron'
    | '/app/system/dashboard-settings'
    | '/app/system/files'
    | '/app/system/health'
    | '/app/system/jobs'
    | '/app/system/notifications'
    | '/app/system/performance'
    | '/app/system/roles'
    | '/app/system/security'
    | '/app/system/support'
    | '/app/system/users'
    | '/app/conversations/'
    | '/app/messages/'
    | '/app/participants/'
    | '/app/system/'
    | '/app/conversations/$id/edit'
    | '/app/messages/$id/edit'
    | '/app/participants/$id/edit'
    | '/app/system/support/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/chat'
    | '/app/data-backup'
    | '/app/profile'
    | '/app/settings'
    | '/app/sync'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/conversations/new'
    | '/app/messages/new'
    | '/app/participants/new'
    | '/app/system/activity'
    | '/app/system/cron'
    | '/app/system/dashboard-settings'
    | '/app/system/files'
    | '/app/system/health'
    | '/app/system/jobs'
    | '/app/system/notifications'
    | '/app/system/performance'
    | '/app/system/roles'
    | '/app/system/security'
    | '/app/system/support'
    | '/app/system/users'
    | '/app/conversations'
    | '/app/messages'
    | '/app/participants'
    | '/app/system'
    | '/app/conversations/$id/edit'
    | '/app/messages/$id/edit'
    | '/app/participants/$id/edit'
    | '/app/system/support/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/chat'
    | '/app/data-backup'
    | '/app/profile'
    | '/app/settings'
    | '/app/sync'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/conversations/new'
    | '/app/messages/new'
    | '/app/participants/new'
    | '/app/system/activity'
    | '/app/system/cron'
    | '/app/system/dashboard-settings'
    | '/app/system/files'
    | '/app/system/health'
    | '/app/system/jobs'
    | '/app/system/notifications'
    | '/app/system/performance'
    | '/app/system/roles'
    | '/app/system/security'
    | '/app/system/support'
    | '/app/system/users'
    | '/app/conversations/'
    | '/app/messages/'
    | '/app/participants/'
    | '/app/system/'
    | '/app/conversations/$id/edit'
    | '/app/messages/$id/edit'
    | '/app/participants/$id/edit'
    | '/app/system/support/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-backup': {
      id: '/app/data-backup'
      path: '/data-backup'
      fullPath: '/app/data-backup'
      preLoaderRoute: typeof AppDataBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sync': {
      id: '/app/sync'
      path: '/sync'
      fullPath: '/app/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/conversations/': {
      id: '/app/conversations/'
      path: '/conversations'
      fullPath: '/app/conversations/'
      preLoaderRoute: typeof AppConversationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations/new': {
      id: '/app/conversations/new'
      path: '/conversations/new'
      fullPath: '/app/conversations/new'
      preLoaderRoute: typeof AppConversationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/new': {
      id: '/app/messages/new'
      path: '/messages/new'
      fullPath: '/app/messages/new'
      preLoaderRoute: typeof AppMessagesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/': {
      id: '/app/participants/'
      path: '/participants'
      fullPath: '/app/participants/'
      preLoaderRoute: typeof AppParticipantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/new': {
      id: '/app/participants/new'
      path: '/participants/new'
      fullPath: '/app/participants/new'
      preLoaderRoute: typeof AppParticipantsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/': {
      id: '/app/system/'
      path: '/system'
      fullPath: '/app/system/'
      preLoaderRoute: typeof AppSystemIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/activity': {
      id: '/app/system/activity'
      path: '/system/activity'
      fullPath: '/app/system/activity'
      preLoaderRoute: typeof AppSystemActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/cron': {
      id: '/app/system/cron'
      path: '/system/cron'
      fullPath: '/app/system/cron'
      preLoaderRoute: typeof AppSystemCronRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/dashboard-settings': {
      id: '/app/system/dashboard-settings'
      path: '/system/dashboard-settings'
      fullPath: '/app/system/dashboard-settings'
      preLoaderRoute: typeof AppSystemDashboardSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/files': {
      id: '/app/system/files'
      path: '/system/files'
      fullPath: '/app/system/files'
      preLoaderRoute: typeof AppSystemFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/health': {
      id: '/app/system/health'
      path: '/system/health'
      fullPath: '/app/system/health'
      preLoaderRoute: typeof AppSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/jobs': {
      id: '/app/system/jobs'
      path: '/system/jobs'
      fullPath: '/app/system/jobs'
      preLoaderRoute: typeof AppSystemJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/notifications': {
      id: '/app/system/notifications'
      path: '/system/notifications'
      fullPath: '/app/system/notifications'
      preLoaderRoute: typeof AppSystemNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/performance': {
      id: '/app/system/performance'
      path: '/system/performance'
      fullPath: '/app/system/performance'
      preLoaderRoute: typeof AppSystemPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/roles': {
      id: '/app/system/roles'
      path: '/system/roles'
      fullPath: '/app/system/roles'
      preLoaderRoute: typeof AppSystemRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/security': {
      id: '/app/system/security'
      path: '/system/security'
      fullPath: '/app/system/security'
      preLoaderRoute: typeof AppSystemSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/support': {
      id: '/app/system/support'
      path: '/system/support'
      fullPath: '/app/system/support'
      preLoaderRoute: typeof AppSystemSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/users': {
      id: '/app/system/users'
      path: '/system/users'
      fullPath: '/app/system/users'
      preLoaderRoute: typeof AppSystemUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations/$id/edit': {
      id: '/app/conversations/$id/edit'
      path: '/conversations/$id/edit'
      fullPath: '/app/conversations/$id/edit'
      preLoaderRoute: typeof AppConversationsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$id/edit': {
      id: '/app/messages/$id/edit'
      path: '/messages/$id/edit'
      fullPath: '/app/messages/$id/edit'
      preLoaderRoute: typeof AppMessagesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/participants/$id/edit': {
      id: '/app/participants/$id/edit'
      path: '/participants/$id/edit'
      fullPath: '/app/participants/$id/edit'
      preLoaderRoute: typeof AppParticipantsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/system/support/$id': {
      id: '/app/system/support/$id'
      path: '/$id'
      fullPath: '/app/system/support/$id'
      preLoaderRoute: typeof AppSystemSupportIdRouteImport
      parentRoute: typeof AppSystemSupportRoute
    }
  }
}

interface AppSystemSupportRouteChildren {
  AppSystemSupportIdRoute: typeof AppSystemSupportIdRoute
}

const AppSystemSupportRouteChildren: AppSystemSupportRouteChildren = {
  AppSystemSupportIdRoute: AppSystemSupportIdRoute,
}

const AppSystemSupportRouteWithChildren =
  AppSystemSupportRoute._addFileChildren(AppSystemSupportRouteChildren)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDataBackupRoute: typeof AppDataBackupRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSyncRoute: typeof AppSyncRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConversationsNewRoute: typeof AppConversationsNewRoute
  AppMessagesNewRoute: typeof AppMessagesNewRoute
  AppParticipantsNewRoute: typeof AppParticipantsNewRoute
  AppSystemActivityRoute: typeof AppSystemActivityRoute
  AppSystemCronRoute: typeof AppSystemCronRoute
  AppSystemDashboardSettingsRoute: typeof AppSystemDashboardSettingsRoute
  AppSystemFilesRoute: typeof AppSystemFilesRoute
  AppSystemHealthRoute: typeof AppSystemHealthRoute
  AppSystemJobsRoute: typeof AppSystemJobsRoute
  AppSystemNotificationsRoute: typeof AppSystemNotificationsRoute
  AppSystemPerformanceRoute: typeof AppSystemPerformanceRoute
  AppSystemRolesRoute: typeof AppSystemRolesRoute
  AppSystemSecurityRoute: typeof AppSystemSecurityRoute
  AppSystemSupportRoute: typeof AppSystemSupportRouteWithChildren
  AppSystemUsersRoute: typeof AppSystemUsersRoute
  AppConversationsIndexRoute: typeof AppConversationsIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppParticipantsIndexRoute: typeof AppParticipantsIndexRoute
  AppSystemIndexRoute: typeof AppSystemIndexRoute
  AppConversationsIdEditRoute: typeof AppConversationsIdEditRoute
  AppMessagesIdEditRoute: typeof AppMessagesIdEditRoute
  AppParticipantsIdEditRoute: typeof AppParticipantsIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDataBackupRoute: AppDataBackupRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSyncRoute: AppSyncRoute,
  AppIndexRoute: AppIndexRoute,
  AppConversationsNewRoute: AppConversationsNewRoute,
  AppMessagesNewRoute: AppMessagesNewRoute,
  AppParticipantsNewRoute: AppParticipantsNewRoute,
  AppSystemActivityRoute: AppSystemActivityRoute,
  AppSystemCronRoute: AppSystemCronRoute,
  AppSystemDashboardSettingsRoute: AppSystemDashboardSettingsRoute,
  AppSystemFilesRoute: AppSystemFilesRoute,
  AppSystemHealthRoute: AppSystemHealthRoute,
  AppSystemJobsRoute: AppSystemJobsRoute,
  AppSystemNotificationsRoute: AppSystemNotificationsRoute,
  AppSystemPerformanceRoute: AppSystemPerformanceRoute,
  AppSystemRolesRoute: AppSystemRolesRoute,
  AppSystemSecurityRoute: AppSystemSecurityRoute,
  AppSystemSupportRoute: AppSystemSupportRouteWithChildren,
  AppSystemUsersRoute: AppSystemUsersRoute,
  AppConversationsIndexRoute: AppConversationsIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppParticipantsIndexRoute: AppParticipantsIndexRoute,
  AppSystemIndexRoute: AppSystemIndexRoute,
  AppConversationsIdEditRoute: AppConversationsIdEditRoute,
  AppMessagesIdEditRoute: AppMessagesIdEditRoute,
  AppParticipantsIdEditRoute: AppParticipantsIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
